### ISSUE TITLE
Export IssuesUpdateEndpoint

### ISSUE THREAD

**Issue by sarvaje** [octokit/types.ts#119]
This type is defined, but is not exported. It would be nice have it exported so we can use it to type some helper methods.

Right now I'm copy/pasting the type from `generated/endpoints.ts` which is not the best solution.

**Comment by gr2m** [comment]
you can access all the types you need using the exported `Endpoint` type, see https://github.com/octokit/types.ts#get-parameter-and-response-data-types-for-a-rest-api-endpoint

For example, to get the response type for [`PATCH /repos/:owner/:repo/issues/:issue_number`](https://developer.github.com/v3/issues/#update-an-issue), you can do this

```ts
const { Endpoints } = require("@octokit/types");
type IssuesUpdateResponse = Endpoints["PATCH /repos/:owner/:repo/issues/:issue_number"]["response"]
```

Does that work for you?

I am considering to export the named types, too, but there are a lot of name changes happening right now as part of a big audit. I'll look into that again in 2-3 months

**Comment by sarvaje** [comment]
@gr2m thanks for your quick response.

Your solution works well just for someone else having the same "problem", because I'm looking for the parameters, the exact type will be:

```ts
type IssuesUpdateEndpoint = Endpoints['PATCH /repos/:owner/:repo/issues/:issue_number']['parameters'];
```
