### ISSUE TITLE
Use TypeSript's Date type

### ISSUE THREAD

**Issue by BrunoBlanes** [octokit/types.ts#146]
**What’s missing?**
This module doesn't take advantage of the TypeScript's `Date` type and instead uses `string`.

**Why?**
To be able to natively take advantage of all the methods that comes with the `Date` type.

**Alternatives you tried**
If I wanted to use `Date` methods I would have to some manual parsing.

**Comment by gr2m** [comment]
Could you be more specific where you think we should use the `Date` type? As far as I know, all the timestamp keys are strings, they are not Date instances

**Comment by BrunoBlanes** [comment]
Indeed they are all strings, but would it be possible to convert them to `Date` by using the type constructor `Date(value: string)`?
My point being that it would be useful to be able to use the `Date.get` methods.

**Comment by gr2m** [comment]
I think that's something you'd do in your code. The timestamp strings can directly be used as argument with the `new Date(timestamp)` constructor. If we created these date instances all the time we would waste a lot of CPU/memory

**Comment by BrunoBlanes** [comment]
I guess you are right, I did not think that creating them would mean a significant impact on performance, but then again, JS is all about not wasting anything.
Thanks.

**Comment by gr2m** [comment]
I'll close the issue as it's not actionable. Feel free to comment if you have more questions
