### ISSUE TITLE
`author_association` missing from pull request review type.

### ISSUE THREAD

**Issue by reitermarkus** [octokit/types.ts#221]
**What happened?**

I have these types:

```ts
import * as github from '@actions/github'
export type Octokit = ReturnType<typeof github.getOctokit>
export type Review = GetResponseDataTypeFromEndpointMethod<Octokit['pulls']['getReview']>
```

The documentation (https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#get-a-review-for-a-pull-request) says there should be a `author_association: string` field on this type.

The type `Review` above contains all fields listed in the documentation up to `commit_id`, as seen in this error:

```
Type '{ id: number; node_id: string; user: { login: string; id: number; node_id: string; avatar_url: string; gravatar_id: string; url: string; html_url: string; followers_url: string; following_url: string; gists_url: string; starred_url: string; subscriptions_url: string; organizations_url: string; repos_url: string; events_url: string; received_events_url: string; type: string; site_admin: boolean; }; body: string; state: string; html_url: string; pull_request_url: string; _links: { html: { href: string; }; pull_request: { href: string; }; }; submitted_at: string; commit_id: string; }' has no properties in common with type '{ author_association?: string | undefined; }'.
```

**What did you expect to happen?**

I expected this type to have a `author_association: string` field.

**Comment by gr2m** [comment]
I cannot help with `@actions/github`, most likely their internal Octokit version is not up-to-date with the latest `@octokit/types`. check with `npm ls` if you have the latest versions of `@octokit/rest` and `@octokit/types` in your dependency tree.

To get response types, you can now import them from https://github.com/octokit/openapi-types.ts which is a 1:1 TypeScript transpilation from GitHub's OpenAPI spec. I'll update the README and deprecate `GetResponseDataTypeFromEndpointMethod` soon.

You want

```
import { components }  from "@octokit/openapi-types"
type Review = components["schemas"]["pull-request-review"]
```

`author_association` is defined correctly

<img width="680" alt="image" src="https://user-images.githubusercontent.com/39992/101265268-edd75180-36f9-11eb-854b-2008553a8f1b.png">

**Comment by reitermarkus** [comment]
> most likely their internal Octokit version is not up-to-date

Yeah, that's probably it.

> check with npm ls if you have the latest versions of @octokit/rest and @octokit/types in your dependency tree

It seems like I don't have `@octokit/rest` in my dependency tree at all. I guess `@octokit/plugin-rest-endpoint-methods` is the common lower-level dependency, which is up-to-date at version `4.4.1`.

I will take a look at `@octokit/openapi-types`.

**Comment by reitermarkus** [comment]
Thanks, switching `@octokit/openapi-types` solved this issue.

**Comment by gr2m** [comment]
Glad you got it working again!

> I guess `@octokit/plugin-rest-endpoint-methods` is the common lower-level dependency, which is up-to-date at version `4.4.1`.

Correct, thanks for checking.
