### ISSUE TITLE
Why is this library designed as it is?

### ISSUE THREAD

**Issue by peey** [octokit/types.ts#233]
I'm new to typescript so I apologize if I'm missing something, and there seem to be no design-overview documentation.

I don't understand why I can't just rely on the return type of e.g. `ocotokit.pulls.create` being automatically picked up by my editor than me having to refine it from `any` to `type X = Endpoints["POST /repos/{owner}/{repo}/pulls"]["response"]` or using `GetResponseTypeFromEndpointMethod`

Normally I wouldn't even have to worry about the types, and as long as I specify the right keys in the object literal that I use as the argument and I use the right properties on the returned object, I'm good to go.

I also have a less important second question: is there no parameter/argument type equivalent to `GetResponseTypeFromEndpointMethod`?

**Comment by oscard0m** [comment]
Thanks for opening this issue @peey 

Would it be possible to share with us a small piece of code where you experience the problem (or maybe screenshots?).

Thanks

**Comment by peey** [comment]
I apologize, I think I had some misconfiguration. Now VSCode does pick up types automatically.

When it didn't, I looked at npm page of `@octokit/types` first instead of changing my code. And then reading the docs there confused me and I thought that I'm supposed to enforce return types myself using stuff like in the given example:

```
type listUserReposParameters = Endpoints["GET /repos/{owner}/{repo}"]["parameters"];
type listUserReposResponse = Endpoints["GET /repos/{owner}/{repo}"]["response"];

```
