### ISSUE TITLE
"GET /repos/{owner}/{repo}/commits" seems to have the wrong type for the commit field

### ISSUE THREAD

**Issue by resolritter** [octokit/types.ts#245]
**Version**

```
    "@octokit/rest": "^18.0.14",
    "@octokit/webhooks": "^7.21.0"
```

**What happened?**

`Endpoints["GET /repos/{owner}/{repo}/commits"]["response"]` does not match what's actually returned in the endpoint. As an evidence, see: https://api.github.com/repos/octokit/types.ts/commits. For instance, it's missing the `parents` field.

The correct type for the items looks like  `StatusEvent["commit"]` from https://github.com/octokit/webhooks/blob/fc8d5d284f936a5cddb952816f692fb4239edf7b/schema.d.ts#L7546.

**Comment by gr2m** [comment]
The type seems to be set correctly in `@octokit/types` (6.5.1)

<img width="633" alt="image" src="https://user-images.githubusercontent.com/39992/105763482-b1122480-5f0a-11eb-9113-0bb92f5df70d.png">

Can you check if you have the latest version in your dependency tree?

```
npm ls @octokit/types
```

**Comment by resolritter** [comment]
I am on 6.5.0.

I was wrong about `parents` missing. Looking at it again, I think what happened is: I tried destructuring possibly undefined and the compiler error message made me think it was not available in this type.

Specifically, I was trying to get the `author` and `comitter` fields. My jump-to-definition landed me on `node_modules/@octokit/openapi-types/generated/types.ts` line `25619` where I now clearly see the following:


```
      author: components["schemas"]["simple-user"] | null;
      committer: components["schemas"]["simple-user"] | null;
```

I suppose the confusion is in the same spirit as [this one](https://github.com/github/rest-api-description/issues/114)... I'm not sure if those fields should be nullable but, either way, it wouldn't be fixed here, I suppose.

Thank you for your time.

**Comment by gr2m** [comment]
The types are directly derived from GitHub's OpenAPI spec which they started to publish recently:
https://github.com/github/rest-api-description/

If you find a problem with missing keys or keys flagged in correctly as (not) required, filing an issue there would be the right place. I'm not sure if there is some special case where `author`/`committer` could be `null`, maybe when an account gets deleted? https://github.com/github/rest-api-description would be the right place to ask these questions
