### ISSUE TITLE
Export types like `PullsListResponse` or `PullsGetResponse`

### ISSUE THREAD

**Issue by a7madgamal** [octokit/types.ts#25]
```
const octokit = new Octokit(options)

  const { data: pulls } = await octokit.pulls.list(options)
```
how can I extract types for the `pulls` array?

**Comment by a7madgamal** [comment]
I somehow managed to get around it (and got 10% more TS expert) by doing this magic:
```
import { PromiseValue } from 'type-fest'
type PullsListResponseItems = PromiseValue<
  ReturnType<InstanceType<typeof Octokit>['pulls']['list']>
>['data']
```

**Comment by gr2m** [comment]
I'll be looking into this as soon as I can. There is some previous discussion here: https://github.com/octokit/rest.js/issues/1624

**Comment by gr2m** [comment]
We are continuing the discussion at https://github.com/octokit/rest.js/discussions/1697

**Comment by httpete** [comment]
I did this and it seemed ok:

```
import { Octokit, RestEndpointMethodTypes } from '@octokit/rest';
type PullsListResponseData = RestEndpointMethodTypes['pulls']['list']['response']['data'];
```

**Comment by gr2m** [comment]
We do have https://github.com/octokit/openapi-types.ts now, I recommend to use that. It's used by `@octokit/types`, so it won't add to your dependencies size by adding `@octokit/openapi-types` as direct dependency to your project.

```js
import { components } from '@octokit/openapi-types';
type PullsListResponseData = components["schemas"]["pull-request-simple"][]
```

[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYwuCA7AphmBnOAXzgDMo04ByAAQmRggGtgYB6CMHAQzGAFoYAT055KAbgBQQznAAKAVwA2ivABlgeGACUseSBjxYAIlxhc4AXhRp9OfAG0ARHmQALLCC55HAXSdglRT4oLABHeV0YPjxQMEUsX3sfIA)
