### ISSUE TITLE
How to narrow down Types for a `octokit.repos.getContent()` response?

### ISSUE THREAD

**Issue by adam-arold** [octokit/types.ts#267]
I'm trying to read the contents of a directory and the return type of `octokit.repos.getContent` is a type union that has many possible values.

I'm trying to narrow the return value of `getContent` to only one of those options, it looks like this:

```
"content-directory": {
    type: string;
    size: number;
    name: string;
    path: string;
    content?: string;
    sha: string;
    url: string;
    git_url: string | null;
    html_url: string | null;
    download_url: string | null;
    _links: {
        git: string | null;
        html: string | null;
        self: string;
    };
}[]
```

I created a `type` out of it:

```
type DirectoryItems = components["schemas"]["content-directory"];
```

and now I'm trying to use it in a type guard:

```
const { data } = await octokit.repos.getContent({
    // ...
});

if(data instanceof DirectoryItems) {

}
```

but it says 

> 'DirectoryItems' only refers to a type, but is being used as a value here.

How can I narrow the type of `data` to make sure that it is indeed an array of "content-directory" items? Is there an example somewhere on how to use TypeScript with Octokit?

**Comment by gr2m** [comment]
You can check if the response data is an array. Try this

```js
const { Octokit } = require("@octokit/rest");

run();

async function run() {
  const octokit = new Octokit();

  const { data } = await octokit.repos.getContent({
    owner: "gr2m",
    repo: "sandbox",
    path: "test-file",
  });

  // ignore non-directory responses
  if (!Array.isArray(data)) {
    return;
  }

  for (const item of data) {
    console.log(item
  }
}
```

**Comment by adam-arold** [comment]
But what will be the type of `item` then? VS Code just complains that it can't find the fields I'm trying to access. There must be some nice way of doing this in Typescript.

**Comment by gr2m** [comment]
You can use `if ("property" in item) { ... }` as type guard

But I think that directory array items do not have all the properties as the items do that you get in the root response.

You can get the type `item.type` and `item.path`, then request the items you want again, e.g. to retrieve the file contents.

**Comment by adam-arold** [comment]
I'll rephrase this then. I know how the API works but what is a simple and effective way of using this API? That doesn't involve writing 50 LOC for extracting data from a simple JSON result?

**Comment by adam-arold** [comment]
This seems to work:

```typescript
const octokit = new Octokit({
    auth: process.env.GITHUB_API_TOKEN,
});

type DirectoryItem = GetResponseDataTypeFromEndpointMethod<
    typeof octokit.repos.getContent
>;
export class GitHubPostQueryService implements PostQueryService {

    async findAll(): Promise<Post[]> {
        const { data } = await octokit.repos.getContent({
            // ...
        });
        if (Array.isArray(data)) {
            data.forEach((element) => {
                if(element as DirectoryItem) {
                    // ...
                }
            });
        }
        // ...
    }
}
```

Is this the right way to do it?

**Comment by gr2m** [comment]
You can get sub-schemas directly from `@octokit/openapi-types`. It's derived directly from GitHub's OpenAPI schema, and we consider changes of names etc breaking changes, so you are safe to rely on it. The `GetResponseDataTypeFromEndpointMethod` helper is something we introduced as a workaround before we had `@octokit/openapi-types`

```ts
import { Octokit } from "@octokit/rest";
import { components } from "@octokit/openapi-types";

const octokit = new Octokit({
  auth: process.env.GITHUB_API_TOKEN,
});

type DirectoryItem = components["schemas"]["content-directory"][number];

export async function findAll(): Promise<DirectoryItem[]> {
  const { data } = await octokit.repos.getContent({
    owner: "owner",
    repo: "repo",
    path: "path/to/files",
  });

  if (!Array.isArray(data)) return [];

  return data;
}
```

**Comment by adam-arold** [comment]
I see. This looks great. I'm a bit new to Typescript and this just blows my mind:

```
type DirectoryItem = components["schemas"]["content-directory"][number];
```

This is not possble in any other typed language I know (deriving types from data structures). But If I"m right this will work properly and will serve as a proper type guard, right?

```typescript
import { Octokit } from "@octokit/rest";
import { components } from "@octokit/openapi-types";

const octokit = new Octokit({
  auth: process.env.GITHUB_API_TOKEN,
});

type DirectoryItem = components["schemas"]["content-directory"][number];

export async function findAll(): Promise<DirectoryItem[]> {
  const { data } = await octokit.repos.getContent({
    owner: "owner",
    repo: "repo",
    path: "path/to/files",
  });

  if (!Array.isArray(data)) return [];
    data.forEach((element) => {
      if(element as DirectoryItem) {
       // ...
       }
   });
  return data;
}
```

**Comment by gr2m** [comment]
> ```ts
> `element as DirectoryItem`
> ```

I don't think that is needed. After the `Array.isArray(data)` check, `data` should be typed as an array of `DirectoryItem` already.

**Comment by dpacmittal** [comment]
```typescript
if("content" in response.data) {
   // you can read response.data.content in this block
}
```

This worked for me finally when trying to access the `content` property.

**Comment by gr2m** [comment]
Here is a [TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAeigFMBnGMgbgChOCBXAO3TAI-OIwAeYRugA8AFQB8ACgDuACwCGMAFxw5ASkS5udOnDUwYYZttMBzHGt4AjAHSoSdahmww6MAE8pZlcYZjpgZmZeFjoAJgA2AHZOCUhYOA1mAMFCASEROBgWGABJKJjEpKVDBE44OA9+VjhvWngAXjh+RhUUGl8arnrGkRakABMtDTh8Lo0VDRxWgZxXJkgQu0YYAGERYv4YJTqGhogVHqhdMjsoOJAyABoRho2IG+YNfgnnCHFnq84GAtGobsVWABaAjAAA2jEBDVw+mGDVMcGAdn40EY3REkImwCYNCgATgTGYkGaLBGwAIcCUAEIAIJQKAaAKuSKs9kBJRTGAafS1IFMGC8KD8LhI7gNAjQBlNFo4RikCD0gVCxBAtLSGAyVhQYD8OzKFUgVz8DQgRj6EbGXBAA) to show how to narrow down types for a `octokit.repos.getContent()` response

Let me know if you have any further questions

**Comment by jonioni** [comment]
Thanks  @adam-arold for raising up the question and @gr2m for providing the workable solution. The `@octokit/openapi-types` works well. But how do we know the name `"content-directory"` in the first place? No where can this name be found in either the GitHub REST API page or the OpenAPI definition file.

And for the get contents api, types extracted from both the `Endpoints` (`@octokit/types`) and `RestEndpointMethodTypes` (`@octokit/rest`) are overly general and problematic: E.g.
```ts 
type getContentResponseData = Endpoints["GET /repos/{owner}/{repo}/contents/{path}"]["response"]["data"];
// type getContentResponseData = RestEndpointMethodTypes["repos"]["getContent"]["response"]["data"];

const { data } = await client.repos.getContent({...});
(data as getContentResponseData).content // Type Error: property 'content' does not exist on type '{ type: string; size: number; name: string; path: string; content?: string; sha: string; url: string; git_url: string; html_url: string; download_url: string; _links: { git: string; html: string; self: string; }; }[] | { ...; } | { ...; } | { ...; }'.
```

Additionally, to use the `GetResponseDataTypeFromEndpointMethod` (`@octokit/types`), the octokit function handle must be passed (as indicated in the README):

```js
type CreateLabelResponseType = GetResponseTypeFromEndpointMethod<
  typeof octokit.issues.createLabel
>;
```

But for top-level type declaration this requires a top-level Octokit instance `octokit` being declared as well. What if user doesn't want to instantiate the client in the global scope and would like to pass in as function argument instead?

Overall these issues make the development with Typescript utterly confusing and time consuming.

**Comment by gr2m** [comment]
The response data type at `Endpoints["GET /repos/{owner}/{repo}/contents/{path}"]["response"]["data"];` is a union of different types. You can access the respective types from `@octokit/openapi-types`.

We will remove the `GetResponseTypeFromEndpointMethod` Generic, it was added before we had `@octokit/openapi-types`, so I wouldn't rely on it

**Comment by jonioni** [comment]
Thanks for the explanation. Hope in the future `@octokit/types` and `@octokit/openapi-types` can be merged so there will be less confusion on which library to use. For now it seems we should stick to `@octokit/openapi-types` for response data handling.

**Comment by thien-do** [comment]
I think it's a bit more reliable to rely on the `type`:

```ts
const { data } = await octokit.request(/* ... */);
if (Array.isArray(data)) return /* folder */
switch (data.type) {
  case "file": // data.content is string
  case ...
}
```

**Comment by Vity01** [comment]
my solution for somebody else searching...
```
    return octokitClient.repos
      .getContent({
        owner,
        repo,
        path: filepath,
      })
      .then( ({data}) => {
        if (Array.isArray(data)) {
          return '';
        }
        if (data.type === 'file' && data.size > 0) {
          return Buffer.from(data.content!, 'base64').toString('utf-8');
        }
        return '';
      });
```

**Comment by oenu** [comment]
> my solution for somebody else searching...
> 
> ```
>     return octokitClient.repos
>       .getContent({
>         owner,
>         repo,
>         path: filepath,
>       })
>       .then( ({data}) => {
>         if (Array.isArray(data)) {
>           return '';
>         }
>         else if (data.type === 'file' && data.size > 0) {
>           return Buffer.from(data.content!, 'base64').toString('utf-8');
>         }
>         return '';
>       });
> ```
Would just make that an explicit else, lest issues arise from forgetting a return. Good fix though!
