### ISSUE TITLE
`Endpoints["GET /repos/{owner}/{repo}/commits/{ref}"]` response type is incomplete

### ISSUE THREAD

**Issue by ojab** [octokit/types.ts#284]
**What happened?**

`Endpoints["GET /repos/{owner}/{repo}/git/commits/{commit_sha}"]` has no `files` field in response type.

**What did you expect to happen?**

It has `files` field.

**What the problem might be**

Content in openapi-types is `"application/json": components["schemas"]["git-commit"];`, I suppose it should be `"application/json": components["schemas"]["commit"];` (which has `files?` field).

**Comment by gr2m** [comment]
could you do me a favor and report this issue in https://github.com/github/rest-api-description, similar to e.g. https://github.com/github/rest-api-description/issues/228? I can do it myself but have other priorities right now. If you could report it we would get it fixed faster

**Comment by ojab** [comment]
Sure, will do tomorrow.
(CONTRIBUTING.md should probably be fixed. it mentions `@octokit/plugin-paginate-rest` right now and I was kinda lost in which package this stuff should go)

**Comment by gr2m** [comment]
> (CONTRIBUTING.md should probably be fixed. it mentions `@octokit/plugin-paginate-rest` right now and I was kinda lost in which package this stuff should go)

Done, sorry for that!

**Comment by ojab** [comment]
Ok, this one is bogus, I've looked into `octokit.repos.getCommit` docs and used `octokit.git.getCommit` in the code :facepalm: 

>Done, sorry for that!
I was thinking about adding a link to https://github.com/github/rest-api-description since types are actually generated based on it.

**Comment by gr2m** [comment]
> I was thinking about adding a link to https://github.com/github/rest-api-description since types are actually generated based on it.

Good idea! It wasn't the case when I created this repository, but I'll incorporate it now
