### ISSUE TITLE
Property 'POST /repos/{owner}/{repo}/forks{?org,organization}' does not exist on type 'Endpoints'.

### ISSUE THREAD

**Issue by ralphschuler** [octokit/types.ts#303]
**What happened?**
When using the `@octokit/types` repo for my setup with Typescript it throws this error:

```
node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1801:60 - error TS2339: Property 'POST /repos/{owner}/{repo}/forks{?org,organization}' does not exist on type 'Endpoints'.

1801             parameters: RequestParameters & Omit<Endpoints["POST /repos/{owner}/{repo}/forks{?org,organization}"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:1802:33 - error TS2339: Property 'POST /repos/{owner}/{repo}/forks{?org,organization}' does not exist on type 'Endpoints'.

1802             response: Endpoints["POST /repos/{owner}/{repo}/forks{?org,organization}"]["response"];
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**What did you expect to happen?**
I expected the Type def to exists.

**What the problem might be**
[Endpoints.d.ts (L4368)](https://github.com/octokit/types.ts/blob/2df6d7f514d5bf9d47c097cb0795c25af3124daa/src/generated/Endpoints.ts#L4368) seems to be the issue, tsc expets it to be `POST /repos/{owner}/{repo}/forks{?org,organization}` but it is `POST /repos/{owner}/{repo}/forks`.

**Comment by gr2m** [comment]
Sorry for that, it was an incorrect path that temporarily slipped into GitHub's OpenAPI spec and we didn't caught it before it found it's way into Octokit. The problem has been resolved now, but you likely have incompatible versions in your dependency tree. Can you please do

    rm -rf package-lock.json node_modules
    npm install

And try again? This should resolve it?

**Comment by ralphschuler** [comment]
Does work!
