### ISSUE TITLE
Export GetResponseDataType & GetResponseType helpers

### ISSUE THREAD

**Issue by gr2m** [octokit/types.ts#31]
This is a follow up to https://github.com/octokit/rest.js/issues/1624#issuecomment-590436498, https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/47

**What’s missing?**

Example

```ts
import { GetResponseDataType } from "@octokit/types"
import { Octokit } from "@octokit/core";
import { restEndpointMethods } from "./src";

const MyOctokit = Octokit.plugin(restEndpointMethods);
const octokit = new MyOctokit()

type CreateLabelResponseDataType = GetResponseDataType<typeof octokit.issues.createLabel>
```

**Why?**

`@octokit/rest` v16 exported response types, v17 does not. There is a separate issue to export response types (#25). This issue is about exporting helper methods that allow to derive a response type from the REST API endpoint methods.

**Alternatives you tried**

Put the code inline, it's fairly trivial

```ts
type Unwrap<T> = T extends Promise<infer U> ? U : T;
type AnyFunction = (...args) => any
type GetResponseType<T extends AnyFunction> = Unwrap<ReturnType<T>>;
type GetResponseDataType<T extends AnyFunction> = Unwrap<ReturnType<T>>["data"];
```

**Comment by gr2m** [comment]
that shipped in https://github.com/octokit/types.ts/releases/tag/v2.8.0

**Comment by webstech** [comment]
@gr2m I just happened to do an install that pulled v2.8.0 and got this error.  This seems like a breaking change.

```
node_modules/@octokit/types/src/GetResponseTypeFromEndpointMethod.ts:2:21 - error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.

2 type AnyFunction = (...args) => any;
```
noImplicitAny and skipLibCheck  are defaulting in the tsconfig.json.
tsc v3.8.3
