### ISSUE TITLE
`Endpoints["GET /repos/{owner}/{repo}/contents/{path}"]["response"]` does not provide types in case `path` corresponds to a file.

### ISSUE THREAD

**Issue by garg3133** [octokit/types.ts#317]
**What happened?**

I am using the endpoint [`octokit.rest.repos.getContent()`](https://octokit.github.io/rest.js/v18#repos-get-content) in one of my project (I'm working on a GitHub Action). The `path` parameter for this endpoint can be a path to a directory or a file, as documented [here](https://docs.github.com/en/rest/reference/repos#get-repository-content). So, in case of a directory, it returns an array of all files in that directory while in case of file, it returns an object of content and properties of that file. 

Now, when I try to access the contents of the file using `response.data.content`, typescript shows the following error:

![image](https://user-images.githubusercontent.com/39924567/120233126-ba255080-c272-11eb-8327-69285558c198.png)

The same error is displayed if I try to access any property of a file object, like `name`, `type`, etc.

On hover over the `data`, it shows the following types associated with `data`:
```
(property) data: {
    type: string;
    size: number;
    name: string;
    path: string;
    content?: string | undefined;
    sha: string;
    url: string;
    git_url: string | null;
    html_url: string | null;
    download_url: string | null;
    _links: {
        ...;
    };
}[] | {
    ...;
} | {
    ...;
} | {
    ...;
}
```
If you look at the first type, it displays all the properties which should be accessible in `response.data` if the `path` corresponds to a file, but as it has a `[]` ahead of the type, maybe it is assuming that the `response.data` is an array and thus only allowing the use of two properties as shown below:

![image](https://user-images.githubusercontent.com/39924567/120233477-80087e80-c273-11eb-876a-bd797f02af4d.png)

To me, it seems like it is some kind of a mistake while writing types for this endpoint, because even if we consider that it is only taking the `path` of a directory into account and showing the possible types in that case, some of the parameters mentioned in the type object above, like `content`, are not included in the response while accessing the endpoint for the path of a directory. So, maybe the `[]` after the type object is wrong or I don't know.

**Comment by gr2m** [comment]
There are four possible types of results, besides a folder and a file, you can also get a submodule or a symlink, see https://docs.github.com/en/rest/reference/repos#get-repository-content.

You have to check for the presence of the "contents" key before using it. See also https://github.com/octokit/types.ts/issues/267

**Comment by garg3133** [comment]
Thanks a lot, @gr2m for the quick response. This does resolve the issue. Actually, I am new to TypeScript and I'm just amazed to see how well-written TypeScript is to avoid any chance of errors.

**Comment by gr2m** [comment]
I have a love-hate relation ship to TypeScript 🤣 It slows me down _SO MUCH_, probably by a factor of 4 or 5, but the developer experience of folks using @octokit packages with both TypeScript and JavaScript is worth all the sweat and blood.
