### ISSUE TITLE
All User Data property Types are "unknown"

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [octokit/types.ts#360]
## What happened?

After some recent update of the dependency (from `6.19.0` to `6.19.1` according to my CI), the types for user data from `octokit.users.getByUsername` stopped working:

```ts
async function typeBug() {
  let twitter_username: string | null | undefined

  const user = (
    await octokit.users.getByUsername({ username: 'creativecreatorormaybenot' })
  ).data
  twitter_username = user.twitter_username
}
```

In this snippet, the assignment in the last line does not work because `user.twitter_username` has type `unknown`. And this is the case for **all** properties on `user`, i.e. the `"public-user"` type.

Here are some screenshots to illustrate it:

<img width="601" alt="Screen Shot 2021-08-25 at 20 59 13" src="https://user-images.githubusercontent.com/19204050/130864323-40e5051a-6f7b-49a6-8731-321416274ca3.png">
<img width="601" alt="Screen Shot 2021-08-25 at 20 59 29" src="https://user-images.githubusercontent.com/19204050/130864335-c389ecad-9a2e-4de2-bab7-5caa69dea876.png">

## What did you expect to happen?

The type is defined as `string | null` and that should also be the type I get in my code - but it is not.

## What the problem might be

I honestly do not know, however, my CD already failed after [this PR](https://github.com/creativecreatorormaybenot/github-tracker/pull/228), i.e. when `@octokit/rest` was bumped to `18.6.8`, which makes me think this might be a transitive issue.

**Comment by byCedric** [comment]
For anyone running into this, and need a temporary workaround. Extracting the response type to offset the 202 response type, "kind of works" 😄 

```ts
import { Octokit } from 'octokit';

const github = new Octokit();

type GithubUser = Extract<
  Awaited<ReturnType<typeof github.rest.users.getByUsername>>['data'],
  { login: string }
>;

export function fetchUser(username: string) {
  return github.rest.users
    .getByUsername({ username })
    .then((response) => response.data as GithubUser);
}

```
