### ISSUE TITLE
error TS6133: 'Url' is declared but its value is never read.

### ISSUE THREAD

**Issue by huan** [octokit/types.ts#37]
`@octokit/types@2.7.1`

**What happened?**

```
> tsc --noEmit

node_modules/@octokit/types/src/generated/Endpoints.ts:4:1 - error TS6133: 'Url' is declared but its value is never read.

4 import { Url } from "../Url";
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**What did you expect to happen?**

No error

**What the problem might be**

Generated unused import

Related to #36

**Comment by gr2m** [comment]
This should be fixed by https://github.com/octokit/types.ts/pull/36

**Comment by huan** [comment]
Thanks for the reply.

I believe the current NPM version is broken, could we publish a new version to fix that?

**Comment by gr2m** [comment]
How is it broken exactly? Could you please share how I can reproduce your error?

I tried it with `@octokit/endpoint` which has a dependency on `@octokit/types`. I could build it with v2.7.1 without any problem

Make sure you delete your lock filed and node_modules folder, then install again, see if the problem still occurs

**Comment by gr2m** [comment]
sorry I got it

**Comment by gr2m** [comment]
This is fixed in the latest version

**Comment by huan** [comment]
Brilliant!
