### ISSUE TITLE
`Url` is imported but its value is never used

### ISSUE THREAD

**Issue by KamasamaK** [octokit/types.ts#38]
The imported `Url` at https://github.com/octokit/types.ts/blob/6dd34519ab658f2fb3d22bdcdf5189c8e16054ff/src/generated/Endpoints.ts#L4

is unused.

**Comment by gr2m** [comment]
Hm I thought I got that fixed in https://github.com/octokit/types.ts/pull/36, but turnes out I only fixed it in the template, not in the generated file, sorry for that!

**Comment by gr2m** [comment]
that should be fixed in https://github.com/octokit/types.ts/releases/tag/v2.8.0
