### ISSUE TITLE
2.8.0 throws "Rest parameter 'args' implicitly has an 'any[]'"

### ISSUE THREAD

**Issue by bcoe** [octokit/types.ts#40]
**What happened?**

When upgrading from `2.7.1` to `2.8.0` starts throwing the following compile error:

```bash
> gcf-utils@2.0.0 compile /Users/bencoe/google/repo-automation-bots/packages/gcf-utils
> tsc -p .

node_modules/@octokit/request/node_modules/@octokit/types/src/GetResponseTypeFromEndpointMethod.ts:2:21 - error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.

2 type AnyFunction = (...args) => any;
                      ~~~~~~~


Found 1 error.
```

**What did you expect to happen?**

`tsc` to compile the code 😆 

**What the problem might be**

Computers 💻

**Comment by gr2m** [comment]
Sorry for the trouble Ben :( I need to put in a test to prevent that from happening again

**Comment by bcoe** [comment]
@gr2m awesome, thank you!
