### ISSUE TITLE
Build error:  Property does not exist on type 'Endpoints' when moving from 6.34.0 to 6.40.0

### ISSUE THREAD

**Issue by crs-k** [octokit/types.ts#426]
**What happened?**

Builds are now breaking as of 6.40 with a missing property error

**What did you expect to happen?**

No build errors from package

**What the problem might be**

Output of build log:
` node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts(437,60): error TS2339: Property 'POST /content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.`

`node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts(438,33): error TS2339: Property 'POST /content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.`

`node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts(441,60): error TS2339: Property 'POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.`

`node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts(442,33): error TS2339: Property 'POST /repos/{owner}/{repo}/content_references/{content_reference_id}/attachments' does not exist on type 'Endpoints'.`

`Error: Process completed with exit code 2.`

**Comment by timrogers** [comment]
Hi @crs-k! Thanks for reaching out and sorry to hear you’re having issues with Octokit. 

Could you please check your lock file (`package-lock.json` or `yarn.lock`) and share the versions of all the `Octokit` package? This often happens when you have versions that don’t match - of course, the issue could be something else though 😊

**Comment by crs-k** [comment]
hey @timrogers, you are correct. I attempted a couple ways to repair this but ultimately had to delete `node_modules` and `package-lock.json` then from `npm i `again.

Thank you for your help!

**Comment by timrogers** [comment]
Thanks for the update! I’d love to figure out how we can stop this from happening. Can you let me which Octokit packages are explicitly listed in your `package.json`? (not the lock file)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by crs-k** [comment]
Sure thing:
   ` "@octokit/plugin-paginate-rest": "2.21.0",`
    `"@octokit/types": "6.40.0",`
