### ISSUE TITLE
I am not able to destructure value from ['response]['data'].

### ISSUE THREAD

**Issue by kozr** [octokit/types.ts#434]
```typescript
 type OctokitGetEndpoint = Endpoints["GET /repos/{owner}/{repo}/contents/{path}"];
 type OctokitGetEndpointData = Endpoints["GET /repos/{owner}/{repo}/contents/{path}"]['response']['data'];
 // ...

 const getResponse: OctokitGetEndpoint["response"] = await this.getObjectOctokit(key);
 const { sha } = getResponse.data as OctokitGetEndpointData
 // ...

 private async getObjectOctokit(key: string): Promise<OctokitGetEndpoint["response"]> {
    try {
      return this.octokit.request(`GET /repos/{owner}/{repo}/contents/{path}`, {
        owner: this.owner,
        repo: this.repo,
        path: key,
      });
    } catch (error) {
      throw error;
    }
  }
```
I am getting the following error when I try to destructure `sha` from `getResponse.data`. What am I doing wrong?

Property 'sha' does not exist on type '{ type: string; size: number; name: string; path: string; content?: string | undefined; sha: string; url: string; git_url: string | null; html_url: string | null; download_url: string | null; _links: { ...; }; }[] | { ...; } | { ...; } | { ...; }'.ts(2339)

**Comment by gr2m** [comment]
From looking at it, I think you need to change this

```diff
- const { sha } = getResponse.data as OctokitGetEndpointData
+ const { sha } = getResponse.data as OctokitGetEndpointData["response"]["data"]
```

But also the `GET /repos/{owner}/{repo}/contents/{path}` endpoint can result with 4 different types (file, symlink, submodule, directory), and you need to type gate.
