### ISSUE TITLE
"Cannot find module 'http'" when using with Angular

### ISSUE THREAD

**Issue by AdamSiekierski** [octokit/types.ts#44]
I'm trying to use the octokit rest, with my Angular app, but when compiling, the TypeScript compiler throws an error:

```
ERROR in node_modules/@octokit/types/src/RequestRequestOptions.ts:1:23 - error TS2307: Cannot find module 'http'.

    1 import { Agent } from "http";
                            ~~~~~~
```

I assume, it comes from the fact, that the RequestRequestOptions.ts file is trying to import from a node.js http module. The error comes off, when I manually remove the part of file, which causes the error.

**Comment by AdamSiekierski** [comment]
Well, fixed the issue on my own. Just changed the import from this: ``` import { Octokit } from '@octokit/rest'; ``` to this ``` import { Octokit } from '@octokit/rest/dist-web'; ```, and it seems to fix the issue.

**Comment by gr2m** [comment]
It's only type definitions, it's not code that is used in your final code run in browsers, so this really shouldn't be a problem. I think installing `@types/node` as devDependency would resolve the problem, too. 

Importing from `@octokit/rest/dist-web` is not a public API and might change in future

**Comment by AdamSiekierski** [comment]
> It's only type definitions, it's not code that is used in your final code run in browsers, so this really shouldn't be a problem. I think installing `@types/node` as devDependency would resolve the problem, too.
> 
> Importing from `@octokit/rest/dist-web` is not a public API and might change in future

Well, although it wasn't affecting the code that ran in browser, the Angular sometimes didn't want to start the development server up, because of the error in TS compiler. And no, adding ``` @types/node ``` didn't resolve the problem, because it is directly importing a class ``` Agent ``` from node.js ``` http ``` module

**Comment by gr2m** [comment]
🤔 there must  be a better way to resolve the problem. We have lots of TypeScript users that build front-end apps with `@octokit/rest`, but you are the first to report the issue. I wonder why, something must be different in your setup

**Comment by AdamSiekierski** [comment]
I'm using the basic setup, shipped with Angular's default workspace, generated with `ng new` command. I was also thinking, why no one has ever had (or reported) this issue since before. Excluding the ``` node_modules/ ``` in TS config, didn't help.

**Comment by gr2m** [comment]
Dzięki Adam, I'll try to reproduce the problem myself

**Comment by ilyaulyanov** [comment]
@gr2m @AdamSiekierski Same error for me using `yarn@2.0.0-rc.31` & `typescript@3.8.3-pnpify`

Had to add `"@types/node": "^13.11.1" for my package `devDependencies`

**Comment by gr2m** [comment]
@AdamSiekierski ☝️ did that workaround work for you?

**Comment by AdamSiekierski** [comment]
Well, adding ```@types/node``` didn't work out. The error somehow disappears, when I import from ```@octokit/rest/dist-web```. When I checked the ```package.json``` file, I found out that the ```/dist-node``` is declared as "main" import and the ```/dist-web``` is declared as "module". TypeScript always  imports from the "main", which causes the error, and I don't think if I can change it.

**Comment by AdamSiekierski** [comment]
Now figured out, that even importing directly from ```@octokit/rest/dist-node``` hides the error - TypeScript just doesn't import types in this case. So the problem still is in the ```@octokit/types``` package. As I wrote earlier - I don't think that installing ```@types/node``` fixes the problem, because ```RequestRequestOptions.ts``` imports directly a class from node's built in ```http``` module.

**Comment by gr2m** [comment]
> because RequestRequestOptions.ts imports directly a class from node's built in http module.

Only the types, it does not import any code. `@octokit/types` only has type definitions

**Comment by AdamSiekierski** [comment]
> @gr2m @AdamSiekierski Same error for me using `yarn@2.0.0-rc.31` & `typescript@3.8.3-pnpify`
> 
> Had to add `"@types/node": "^13.11.1"` for my package's `devDependencies`

Could you send your ```.tsconfig``` file? I'm wondering if I have something configured wrong.

**Comment by AdamSiekierski** [comment]
Finally found the thing, that caused the issue. Even setting ```"types": ["node"]``` in my ```tsconfig.json``` didn't work, because I was having a ```tsconfig.app.json``` which was extending the base file, with ```"types": []```, so the node types weren't used. Thank you for the support, and sorry for all the fuss ;).
