### ISSUE TITLE
Missing "content" for octokit.rest.repos.getContent API call when returning single file

### ISSUE THREAD

**Issue by lassegit** [octokit/types.ts#440]
**What happened?**

Trying to get `content` attribute like:

```js
const response = await octokit.rest.repos.getContent({ owner, repo, path });
        const content = !Array.isArray(response.data)
          ? response.data.content // Typescript highlights this an missing attribute with the following error below
          : response.data[0].content;
```

Typescript error:

```
Property 'content' does not exist on type '{ type: string; encoding: string; size: number; name: string; path: string; content: string; sha: string; url: string; git_url: string | null; html_url: string | null; download_url: string | null; _links: { ...; }; target?: string | undefined; submodule_git_url?: string | undefined; } | { ...; } | { ...; }'.
  Property 'content' does not exist on type '{ type: string; target: string; size: number; name: string; path: string; sha: string; url: string; git_url: string | null; html_url: string | null; download_url: string | null; _links: { git: string | null; html: string | null; self: string; }; }'.ts(2339)
```

According to the official API, when a single file is returned (in an object) it has the `content` attribute and when the response contains multiple files in an array it shouldn't have the `content` attribute. Source: https://docs.github.com/en/rest/repos/contents#get-repository-content

It seems that the types are mixed around. It suggests `content` only exists when returning multiple files and not a single file.

**Comment by lassegit** [comment]
Using version `"@octokit/types": "^6.41.0",`.

**Comment by timrogers** [comment]
Can you try checking the `type` of the `data`? It could be a symlink or submodule, which doesn't have `content`. If you add that check, then Typescript should be happy - or at least, it is for me locally:

```js
const response = await octokit.rest.repos.getContent({ owner: 'github', repo: 'github', path: 'README.md'});

if (!Array.isArray(response.data) {
  if (response.data.type === 'file') {
    console.log(response.data.content)
  }
}
```

**Comment by oscard0m** [comment]
I think a similar issue was created in the past and this was the way to solve this: https://github.com/octokit/rest.js/issues/32

The issue was blocked by https://github.com/github/rest-api-description/issues/165, but it was solved a few days ago.

**Comment by wolfy1339** [comment]
The types can't know that what you requested is a single file, they represent what can be returned by the API.

As said above, there are also the `symlink` and `submodule` types which do not have a `content` property, which is why you are getting the error

**Comment by lassegit** [comment]
I was missed checking the `content.data?.type === "file"`. It works like:

```js
if (!Array.isArray(content.data) && content.data?.type === "file") {
    console.log(content.data.content);
}
```

Thanks for the quick responses ✌️.
