### ISSUE TITLE
TypeError(property doesn't exist) raised where there shouldn't be one on Endpoints['GET /repos/{owner}/{repo}/branches/{branch}']['response']

### ISSUE THREAD

**Issue by neila** [octokit/types.ts#452]
**What happened?**
Object assigned with type `Endpoints['GET /repos/{owner}/{repo}/branches/{branch}']['response']` spits out TypeError when trying to return a property within it. However, the property does indeed exist and code does run fine.

As per the [github official docs](https://docs.github.com/en/rest/branches/branches#get-a-branch), the response should have the following (nested) property; `{EndpointResponseObject}.commit.commit.tree.url`.

```ts
import {Endpoints} from "@octokit/types"

...

// the function I want to call
const getBranchContentsURL = async (owner: string, repo: string, branch: string) => {
  
  // send get request to github API endpoint and save the response in JSON format
  const branch_git: Endpoints['GET /repos/{owner}/{repo}/branches/{branch}']['response'] =
    await fetch(
      `https://api.github.com/repos/${owner}/${repo}/branches/${branch}`,
      {
        headers: {
          Authorization: 'token ' + process.env.GITHUB_AUTH_TOKEN,
        },
      },
    ).then((response) => response.json());

  // Property "commit" does not exist on type "OctokitResponse<{ name: string; commit: {url: string; sha: string; ......."
  const treeURL: string = branch_git.commit.commit.tree.url;

  // But actually, this console log works fine and outputs the expected URL.
  console.log(treeURL);
  // which means the property "commit.commit.tree.url" does exist in branch_git, as it should.

  return treeURL;
};

```

**What did you expect to happen?**
For the typeerror to not show

**What the problem might be**
I'm not sure. Could there be other response types like `undefined` or `null` that I am not properly considering when calling the object nested property? Or am I simply using the Octokit response type incorrectly?

**Comment by neila** [comment]
Reformatting the async function to

```ts
const getBranchContentsURL = async (
  owner: string,
  repo: string,
  branch: string,
) => {
  const branch_contents: Endpoints['GET /repos/{owner}/{repo}/branches/{branch}']['response'] =
    await fetch(
      `https://api.github.com/repos/${owner}/${repo}/branches/${branch}`,
      {
        headers: {
          Authorization: 'token ' + process.env.GITHUB_AUTH_TOKEN,
        },
      },
    )
      .then((response) => response.json())
      .then((i) => i.commit.commit.tree.url);

  console.log(branch_contents);
  return branch_contents;
};
```

made the TypeError go away. Function still works the same. Weird.
I guess it's not serious enough to call it a bug, but the false error raised in the initial post still stands. Feel free to close or follow up with investigating if interested.

**Comment by timrogers** [comment]
@neila Thanks for reaching out! ✨ 

I think the issue here is that you're declaring with your type declarations that the value of `branch_git` matches the type `Endpoints['GET /repos/{owner}/{repo}/branches/{branch}']['response']`, but that isn't actually true.

`branch_git` contains the parsed JSON response body (thanks to `response.json()`), but `Endpoints['GET /repos/{owner}/{repo}/branches/{branch}']['response']` maps to the [`OctokitResponse` type](https://github.com/octokit/types.ts/blob/master/src/OctokitResponse.ts) which is a wrapper around the response with `headers, `status`, `url` and `data` properties.

What you actually want to do is declare that `branch_git` is the `data` part of the `OctokitResponse`. You can do that like this:

```ts
import { Endpoints } from "@octokit/types"

// the function I want to call
const getBranchContentsURL = async (owner: string, repo: string, branch: string) => {
  
  // send get request to github API endpoint and save the response in JSON format
  const branch_git: Endpoints['GET /repos/{owner}/{repo}/branches/{branch}']['response']['data'] =
    await fetch(
      `https://api.github.com/repos/${owner}/${repo}/branches/${branch}`,
      {
        headers: {
          Authorization: 'token ' + process.env.GITHUB_AUTH_TOKEN,
        },
      },
    ).then((response) => response.json());

  // Property "commit" does not exist on type "OctokitResponse<{ name: string; commit: {url: string; sha: string; ......."
  const treeURL: string = branch_git.commit.commit.tree.url;

  // But actually, this console log works fine and outputs the expected URL.
  console.log(treeURL);
  // which means the property "commit.commit.tree.url" does exist in branch_git, as it should.

  return treeURL;
};
```

Can you try that and let me know how you get on? Typescript seems happy with that when I try it!

**Comment by neila** [comment]
Makes sense. 
Thank you so much, worked on my end as well!
