### ISSUE TITLE
How to access listStargazersForRepo resonse?

### ISSUE THREAD

**Issue by yanshay** [octokit/types.ts#544]
I can't find how to get the data out of ListStargazersForRepo response.
I understand there are several options for response but can't find how to distinguish among them to get to the data.
I seems to me that narrowing should be using the starred_at property but I couldn't get it to work, options I tried are in the code below.
Any help will be appreciated.

Here is my code:

```js
import { Octokit } from '@octokit/rest'
// import {
//   GetResponseTypeFromEndpointMethod,
//   GetResponseDataTypeFromEndpointMethod,
// } from '@octokit/types'

const octokit = new Octokit();

// type ListStargazersForRepoResponse = GetResponseTypeFromEndpointMethod<typeof octokit.activity.listStargazersForRepo>
// type ListStargazersForRepoResponseData = GetResponseDataTypeFromEndpointMethod<typeof octokit.activity.listStargazersForRepo>

(async function run() {
  const response = await octokit.rest.activity.listStargazersForRepo({
    headers: {
      accept: 'application/vnd.github.v3.star+json',
    },
    owner: 'facebook',
    repo: 'react',
    per_page: 2,
    page: 2,
  })

  response.data.forEach((v) => {
    console.log(v.starred_at)
    if (typeof v.starred_at !== 'undefined') {
       
    }
    if ('starred_at' in v && typeof v.starred_at === 'string') {
      
    }
    if (v.starred_at && typeof v.starred_at === 'string') {
       console.log(v.user.login); // v.login also. errors <----- Error
    }
  })
})()

```

This is the error I get:

```
index.ts:43:22 - error TS2339: Property 'user' does not exist on type '{ name?: string | null | undefined; email?: string | null | undefined; login: string; id: number; node_id: string; avatar_url: string; gravatar_id: string | null; url: string; html_url: string; followers_url: string; following_url: string; gists_url: string; starred_url: string; subscriptions_url: string; organizations_url: string; repos_url: string; events_url: string; received_events_url: string; type: string; site_admin: boolean; starred_at?: string | undefined; } | { starred_at: string; user: { name?: string | null | undefined; email?: string | null | undefined; login: string; id: number; node_id: string; avatar_url: string; gravatar_id: string | null; url: string; html_url: string; followers_url: string; following_url: string; gists_url: string; starred_url: string; subscriptions_url: string; organizations_url: string; repos_url: string; events_url: string; received_events_url: string; type: string; site_admin: boolean; starred_at?: string | undefined; } | null; }'.
  Property 'user' does not exist on type '{ name?: string | null | undefined; email?: string | null | undefined; login: string; id: number; node_id: string; avatar_url: string; gravatar_id: string | null; url: string; html_url: string; followers_url: string; following_url: string; gists_url: string; starred_url: string; subscriptions_url: string; organizations_url: string; repos_url: string; events_url: string; received_events_url: string; type: string; site_admin: boolean; starred_at?: string | undefined; }'.
```

**Comment by yanshay** [comment]
I asked ChatGPT and this is what it (or she/he?) came up with:

 ```
 response.data.forEach((v) => {
    console.log(v.starred_at)
    if ('user' in v && typeof v.user === 'object' && v.user !== null) {
      console.log(v.user.login)
      // Access other properties of v.user if needed
    }
```
It works, is that indeed the correct way to narrow in this case?

What confused me was that starred_at is accessible without any narrowing, but in the github docs it should be available only in one of the options.

**Comment by gr2m** [comment]
There is no `.user` property, try `v.login`

You can see an example response at https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#list-stargazers

**Comment by yanshay** [comment]
> There is no `.user` property, try `v.login`
> 
> You can see an example response at https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#list-stargazers

On that page you can see there is also an example 2 which has the` starred_at` at the root of the data and then all other properties move into a `user` structure. For some reason on the top section of the page it doesn't show that in order to get that format of response you need to set the `accept` header to `"application/vnd.github.v3.star+json"`. That can be seen in the section below under "List repositories starred by the authenticated user"(https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#list-repositories-starred-by-the-authenticated-user). And it works.

Anyway, in both cases need to differentiate between the two options of response. Initially I thought it should have been using the `starred_at` property which should exist only in the first example, but seems that the way it translates to typescript type (`starred_at` as optional in both formats) the narrowing should be done using the existence of the user section. 
So even to get to use the Example 1 structure I need to:
```
    if (!('user' in v)) {
      console.login(v.login)
    }
```

**Comment by gr2m** [comment]
Glad you got it to work 👍🏼
