### ISSUE TITLE
Property 'content' does not exist on type 'ReposGetContentsResponseData'

### ISSUE THREAD

**Issue by fogfish** [octokit/types.ts#56]
**What happened?**

```
Property 'content' does not exist on type 'ReposGetContentsResponseData'.
Property 'content' does not exist on type 'ReposGetContentsResponseDataItem[]'.
```

after,  I've migrated my code to  `"@octokit/rest": "^17.6.0"`. The issue is visible at
https://github.com/fogfish/code-build-bot/blob/github-error/apps/webhook/lib/codebuild.ts#L39

The type definition of your library is seemed to be correct but `tsc` cannot see it 

```ts
type ReposGetContentsResponseData =
  | {
      type: string;
      encoding?: string;
      size: number;
      name: string;
      path: string;
      content?: string;
      sha: string;
      url: string;
      git_url: string;
      html_url: string;
      download_url: string | null;
      _links: ReposGetContentsResponseDataLinks;
      target?: string;
      submodule_git_url?: string;
    }
  | Array<ReposGetContentsResponseDataItem>;
```

**What did you expect to happen?**

I would expect that Property 'content' exists on type

**Comment by gr2m** [comment]
You have to handle the case where `x` can be an array. When you make sure that it's not an array before trying to access the `.content` property it should work

**Comment by fogfish** [comment]
Thank you for hit! `octokit/types.ts` do not export `ReposGetContentsResponseData`. Indeed I can do checks and type casting but I have to use my own type definitions. It used to work with `v16`. May be I missing something obvious from `tsc`.

**Comment by gr2m** [comment]
No we no longer export these types from `@octokit/rest`, we do export a new type map though that follows the same name conventions as the method names though, see https://github.com/octokit/rest.js/releases/tag/v17.0.0#typescript

```ts
import { RestEndpointMethodTypes } from "@octokit/rest";

RestEndpointMethodTypes["repos"]["getContents"]["response"]["data"]
```

You can also extract the types directly from the endpoint methods, see [Get response types from endpoint methods](https://github.com/octokit/types.ts/tree/e2df6d46f9657b57f06183f44cf2240c10821c83#get-response-types-from-endpoint-methods)

Does either work for you?

**Comment by fogfish** [comment]
Great! Thank you for comprehensive explanation! It is going to work perfectly for me.
