### ISSUE TITLE
Versioning does not correspond to octokit

### ISSUE THREAD

**Issue by alper** [octokit/types.ts#571]
### Describe the need

Not sure which version of the types to grab here. Why don't the version numbers correspond to the main project?

### Relevant log output

```
src/lib/github.ts:130:3 - error TS2322: Type '{ id: number; node_id: string; name: string; full_name: string; owner: { name?: string | null | undefined; email?: string | null | undefined; login: string; id: number; node_id: string; avatar_url: string; ... 14 more ...; starred_at?: string | undefined; }; ... 79 more ...; allow_forking?: boolean | undefined; }[]' is not assignable to type 'ReposListForOrgResponseData'.
  Type '{ id: number; node_id: string; name: string; full_name: string; owner: { name?: string | null | undefined; email?: string | null | undefined; login: string; id: number; node_id: string; avatar_url: string; ... 14 more ...; starred_at?: string | undefined; }; ... 79 more ...; allow_forking?: boolean | undefined; }' is not assignable to type '{ id: number; node_id: string; name: string; full_name: string; owner: { login: string; id: number; node_id: string; avatar_url: string; gravatar_id: string; url: string; html_url: string; followers_url: string; ... 9 more ...; site_admin: boolean; }; ... 73 more ...; license: { ...; }; }'.
    The types of 'owner.gravatar_id' are incompatible between these types.
      Type 'string | null' is not assignable to type 'string'.
        Type 'null' is not assignable to type 'string'.

130   return repos;
      ~~~~~~
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
> Why don't the version numbers correspond to the main project

there is no main project. The Octokit SDK is decomposed, you can use `@octokit/request`, `@octokit/core`, `octokit`, and some others depending on your use case.

You don't need to define a dependency on `@octokit/types` if you don't want to, it will already be in your dependencies. I would still recommend it though. As long as you keep all your octokit dependencies up to date it should be no problem.

The error you see looks like a tsconfig problem, probably some `*strict` setting, super annoying, but also not much we can do about it on our side.
