### ISSUE TITLE
[BUG]: It could be me but im getting - import/no-unresolved

### ISSUE THREAD

**Issue by ryan-WORK** [octokit/types.ts#593]
### What happened?

I installed the package and attempted to use it like so:
-  `npm i @octokit/types` 
-  I imported it into my project `import { Endpoints } from '@octokit/types'`

At this point it works in the editor and looks perfect. 

I then run `npm run lint` ( `    "lint": "npx eslint . -c ./.github/linters/.eslintrc.yml",`) and I get the following error:

```
    > npx eslint . -c ./.github/linters/.eslintrc.yml

/slow-clap/src/utils.ts
  2:28  error  Unable to resolve path to module '@octokit/types'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

If I add this line  `/*eslint import/no-unresolved: [2, { ignore: ['@octokit/types'] }]*/ ` to the file it resolves the error and all of the logic works as expected.

Like I said in the title it could be me not understanding some configuration, but all of the other `@octokit/*` packages seem to work just fine except for this one. Any help is appreciated.

### Versions

I have tried:
- @octokit/types 12.1.1
- @octokit/types 12.0.0

### Relevant log output

```shell
> npx eslint . -c ./.github/linters/.eslintrc.yml

/slow-clap/src/utils.ts
  2:28  error  Unable to resolve path to module '@octokit/types'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
It's unclear whether this is a problem with `@octokit/types` or the linter or your ts configuration. If you can reproduce a problem on https://www.typescriptlang.org/play we can look into it, otherwise this is not actionable right now. But we can leave it open for a moment to see if others see the same symptom

**Comment by ryan-WORK** [comment]
After messing around with `@octokit/types` in the https://www.typescriptlang.org/play and receiving no errors , I believe that it is related to the `eslint` configuration that I am using.

@gr2m thank you for taking the time to respond. I really appreciate it
