### ISSUE TITLE
Incorrect type for "repos.uploadReleaseAsset"

### ISSUE THREAD

**Issue by hipstersmoothie** [octokit/types.ts#73]
**What happened?**

In octokit v16 `repos.uploadReleaseAsset` accepted `string | object` for the `data` prop.

In octokit v17 it only accepts a `string`. Running the code with `as any` though providing a buffer is still valid.

https://github.com/intuit/auto/blob/master/plugins/upload-assets/src/index.ts#L70

**What did you expect to happen?**

This endpoint should still accept a `Buffer`.

**What the problem might be**

I tried finding the place to contribute it but was unable since it is generated from somewhere else

**Comment by gr2m** [comment]
We might need to implement a workaround for that special case in [`scripts/update-endpoints/typescript.js`](https://github.com/octokit/types.ts/blob/master/scripts/update-endpoints/typescript.js), it's not the first one. It really is a rather odd endpoint

**Comment by gr2m** [comment]
Would appreciate a PR if you or anyone else would like to work on this :)
