### ISSUE TITLE
Typings for /user/repos

### ISSUE THREAD

**Issue by papaia** [octokit/types.ts#88]
**What’s missing?**
Typings for the `/user/repos` endpoint response.

**Why?**
It's currently missing and seems fitting for this project.

**Alternatives you tried**
Typing it myself, not *that* hard, but a little inconvenient, as most of my GH types depend on this package.

**Comment by gr2m** [comment]
The response types are currently generated by parsing GitHubs REST API docs, in this case https://developer.github.com/v3/repos/#list-repositories-for-the-authenticated-user. There is no example response in the section of the `GET /user/repos` endpoint, that's why we don't have types.

The documentation team is aware, I'll update this issue once there is news

**Comment by Papaia** [comment]
@gr2m any updates?

**Comment by gr2m** [comment]
Not yet, sorry

**Comment by mattnotmitt** [comment]
I assume this is why there's no types for the `GET /users/:username/repos` response as well?

**Comment by gr2m** [comment]
We do have types for `GET /users/:username/repos`

<img width="591" alt="image" src="https://user-images.githubusercontent.com/39992/96744201-a8dda280-1379-11eb-886e-e0ab5c4f8cf5.png">

**Comment by mattnotmitt** [comment]
Yes, but `response.data` is `any` which is essentially useless for static checking.

**Comment by gr2m** [comment]
ah yes, indeed. Most issues about missing typings will be resolved by https://github.com/octokit/types.ts/issues/161

**Comment by gr2m** [comment]
We now have a the full response type for `GET /users/:username/repos`

<img width="586" alt="image" src="https://user-images.githubusercontent.com/39992/123559278-e5a33a00-d74f-11eb-9d5b-61cea168a608.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/39992/123559307-13887e80-d750-11eb-880c-914fc8051cd9.png">


[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQHYBNLFTAznAXzgDMoIQ4AiAAQgGMYIBrYGAehgE8wBTXSgFAC6EVLngw+8ALyIiAQ3xpMEbHgDalAOLIAKnDYBXXDyi42CY6dTyQPAmyg9I-ALqanuSGJ6VXw0XE4SXEAJjhZBAUlDCwcXE0dfSMTKEdnCDcPPm8TPyA)
